run:
  tests: true
  build-tags:
    - bench
    - !bench

linters-settings:
  funlen:
    lines: 150
    statements: 80
  depguard:
    rules:
      Main:
        files:
          - $all
          - "!$test"
        allow:
          - $gostd
          - github.com/lib/pq
          - google.golang.org/protobuf/types/known/timestamppb
          - github.com/VictorLeskin/otus_final_project_of_golang_course/internal/models
          - github.com/VictorLeskin/otus_final_project_of_golang_course/internal/api
          - github.com/VictorLeskin/otus_final_project_of_golang_course/internal/bucket 
          - github.com/VictorLeskin/otus_final_project_of_golang_course/internal/config 
          - github.com/VictorLeskin/otus_final_project_of_golang_course/internal/storage 
          - github.com/VictorLeskin/otus_final_project_of_golang_course/internal/storage/memory
          - github.com/VictorLeskin/otus_final_project_of_golang_course/internal/storage/postgres
      Test:
        files:
          - $test
        allow:
          - $gostd
          - github.com/stretchr/testify
          - google.golang.org/protobuf/types/known/timestamppb
issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - dupl
        - gocyclo
        - gosec

linters:
  disable-all: true
  enable:
    - asciicheck
    - depguard
    - dogsled
    - dupl
    - bodyclose
    - durationcheck
    - errorlint
    - exhaustive
    - copyloopvar
    - funlen
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - gofumpt
    - goheader
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - lll
    - makezero
    - misspell
    - nestif
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - stylecheck
    - tagliatelle
    - thelper
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
